- imports/Musella Initial Import 20180404.csv
Loaded, need to push to heroku and run import/export code.
> Initial Upload of Musella Data

- imports/Musella_Remove_1.csv
> Williamhoos musella 3

- README.md
clarified support of crowd custom facet front matter.
> update documentation for import

- Rakefile
The rake task is being run through the `search:bootstrap` task with a default query and limit.
It's also available as a standalone task that receives a search term and a limit, this way it can be used to generate indexes for a particular search.
> Add rake task to add studies from a specific query

- front/app/containers/LandingPage/LandingPage.tsx
add video to home page - need to check how it looks
> add youtube video to home page

- front/app/containers/GenericStudySectionPage/GenericStudySectionPage.tsx
> Handle returns in extra data of studies

- front/app/containers/SearchPage/components/CrumbsBar.tsx
> changing filters bar to default open

- Gemfile
- app/graphql/concerns/auth_helpers.rb
- app/graphql/mutations/sign_in.rb
- app/graphql/mutations/sign_up.rb
- app/models/user.rb
- front/app/containers/LoginPage/SignInPage.tsx
- front/app/containers/LoginPage/SignUpPage.tsx
- front/app/types/globalTypes.ts
Working verison of google oauth that we created from newest version of staging. Does require .env file for Google Secret which will post in CTD slack.
> RTM - Oauth off staging

- app/graphql/mutations/copy_site_view.rb
- app/graphql/mutations/update_site_view.rb
- app/models/site_view.rb
Allows the user to copy a siteviews updates
> Site view graphql

- front/app/components/SiteForm/SearchForm.tsx
-Facet bar, crowdAggs filter is now displaying the correct saved value. 
-All drop-down buttons in SearchForm have been restyled. They now have a Label, and current value is displayed as the button title for an improved UX
> RTM bug fixes for issues #402 and #403

- front/app/containers/App/App.tsx
- front/app/containers/SearchPage/SearchPage.tsx
- front/app/containers/SearchPage/SearchView.tsx
- front/app/containers/SearchPage/components/CrumbsBar.tsx
- front/app/containers/SearchStudyPage/SearchStudyPage.tsx
- front/app/containers/SiteProvider/SiteProvider.tsx
- front/app/containers/StudyPage/StudyPage.tsx
- front/app/containers/WikiPage/WikiPage.tsx
-Url routes now use query strings
-Fixes nex/previous back buttons on study page
> RTM resolves issues #400 and #405

- front/app/containers/App/App.tsx
- front/app/containers/BulkEditPage/BulkEditPage.tsx
- front/app/containers/SearchPage/SearchPage.tsx
Fixes some routing issues. Additionally fixes BulkEditPage breaking due to missingFields (-99999999)
> RTM fixes some routing issues related to issue #414

- front/app/containers/BulkEditPage/BulkEditPage.tsx
- front/app/containers/StudyPage/StudyPage.tsx
Removes deprecated function that was reading the old path and returning said path and appending it to the link. This resulted in an extra "/" being added to the end of our URLparams
> Resolves issue #426

- front/app/components/SiteForm/SearchForm.tsx
- front/app/containers/SearchPage/SearchView.tsx
added a new button option for a magnifying glass/search icon
> issue #418: added search icon

- front/app/components/AuthHeader/AuthHeader.tsx
points to https://home.clinwiki.org/make-a-donation/ with target blank
> add donation link to header on app

- front/app/components/AuthHeader/AuthHeader.tsx
was commented out by null test
> remove old search box

- app/graphql/types/field_display_type.rb
- app/models/site_view.rb
- front/app/components/MultiCrumb/AggCrumb.tsx
- front/app/components/SiteForm/AggField.tsx
- front/app/containers/AggDropDown/AggDropDown.tsx
- front/app/containers/AggDropDown/RangeSelector.tsx
- front/app/containers/SearchPage/components/AggFilterInputUpdater.tsx
- front/app/containers/SearchPage/components/CrumbsBar.tsx
- front/app/types/globalTypes.ts
- Created two Display options Date Range (previously Range) and Number Range
-Both use RangeSelector component, only difference one gives a date selector and formats output accordingly, other is straight text input
> RTM Resolves issue #406- Adds additional functionality to RangeSelector

- app/graphql/types/field_display_type.rb
- app/models/site_view.rb
- front/app/components/MultiCrumb/AggCrumb.tsx
- front/app/components/SiteForm/AggField.tsx
- front/app/containers/AggDropDown/AggDropDown.tsx
- front/app/containers/AggDropDown/RangeSelector.tsx
- front/app/containers/SearchPage/components/AggFilterInputUpdater.tsx
- front/app/containers/SearchPage/components/CrumbsBar.tsx
- front/app/types/globalTypes.ts
Reverts clinwiki-org/clinwiki#446
Something broke, so reverting
> Revert "RTM Resolves issue #406- Adds additional functionality to RangeSelector"

- front/app/containers/SearchPage/SearchPage.tsx
- front/app/containers/SearchPage/components/Aggs.tsx
- front/app/types/globalTypes.ts
> Temporary solution for #417. Adds refresh button to facet bar to refresh page when facets don't load.. 

- .github/FUNDING.yml
- app/graphql/mutations/create_site.rb
- app/graphql/mutations/update_site.rb
- app/graphql/types/site_type.rb
- db/migrate/20200416163941_string_for_theme.rb
- db/schema.rb
- front/app/containers/SiteProvider/SiteProvider.tsx
- front/app/types/globalTypes.ts
String json object for theme information about site theme
> String theme

- front/app/components/SiteForm/MainForm.tsx
- front/app/components/SiteForm/SiteForm.tsx
- front/app/types/SiteFragment.ts
- front/app/types/SiteProviderQuery.ts
Adds ability to edit themes object as a string.
> added the theme config text area in mainForm

- app/services/search_service.rb
> Revert sort to id, changed to sortKind to match front end config.

- db/migrate/20200424150220_site_theme_default_string.rb
- db/schema.rb
Changes the default string for themes to include a color for the facet bar so that it is visible. All future Sites created will have this color theme unless changed.
> 491 theme default string

- front/app/components/SiteForm/AggField.tsx
- front/app/components/SiteForm/SearchForm.tsx
- front/app/containers/AggDropDown/AggDropDown.tsx
Fixes #488 
Originally mutation was added on every keystroke, changed so mutation only happens onBlur. 
Additionally included the fix for #493 
Removing a redundant label in AggField
> RTM Fix for issue #488 and #493

- front/app/components/LoginModal/LoginModal.tsx
- front/app/components/LoginModal/index.tsx
- front/app/containers/LoginPage/SignInPage.tsx
- front/app/containers/SearchPage/components/CrumbsBar.tsx
- front/app/containers/SearchPage/components/ExportToCsvButton.tsx
- front/app/containers/SearchPage/components/ExportToCsvComponent.tsx
> add login modal to export to csv button, show button in logged out state

- front/app/components/FacetCard/AddFacetCard.tsx
- front/app/components/FacetCard/FacetCard.tsx
- front/app/components/StyledComponents/index.ts
- front/app/containers/BulkEditPage/BulkEditView.tsx
- front/app/containers/CrowdPage/CrowdPage.tsx
- front/app/containers/WorkflowPage/SuggestedLabels.tsx
> 511 workflow add labels

- front/app/components/StyledComponents/index.ts
- front/app/containers/LoginPage/EditProfilePage.tsx
- front/app/containers/ProfilePage/ProfileScoreBoard.tsx
- front/app/containers/ProfilePage/RenderReviews.tsx
- front/app/containers/SearchPage/SearchPage.tsx
Changes to the user profile page to show user stats.
Now also includes a list of studies/reviews the user has made.
> Profile view update

- front/app/components/FacetCard/AddFacetCard.tsx
- front/app/components/FacetCard/FacetCard.tsx
- front/app/components/FacetCard/theme.css
- front/app/components/StyledComponents/index.ts
- front/app/containers/AggDropDown/Filter.tsx
- front/app/containers/CrowdPage/CrowdPage.tsx
- front/app/containers/SearchPage/components/CrumbsBar.tsx
- front/app/containers/StudyPage/StudyPage.tsx
- front/app/containers/StudyPage/components/StudyPageSections/StudyPageSection.tsx
- front/app/containers/StudyPage/components/StudyPageSections/StudyPageSections.tsx
- front/app/containers/WorkflowPage/SuggestedLabels.tsx
- front/app/containers/WorkflowPage/WorkflowPage.tsx
- front/app/global-styles.ts
I accidentally merged my branch straight to staging. Merging this revert will merge the changes in my branch 526-workflow-improvements back into staging.
> 526-Workflow-Improvements

- front/app/components/FacetCard/AddDescAuto.tsx
- front/app/components/FacetCard/AddFacetCard.tsx
- front/app/components/FacetCard/AddFieldAuto.tsx
- front/app/components/FacetCard/FacetCard.tsx
- front/app/components/StyledComponents/index.ts
- front/app/containers/WorkflowPage/SuggestedLabels.tsx
Updates for issue #566
1) String Truncation on label titles
2) styling changes for Add label card
3) fixed the bug in description autosuggest box in add label card where typed string was one character behind
4) label autosuggest now pulls labels projectwide
> 566 crowd autosuggest updates

- front/app/components/FacetCard/AddFacetCard.tsx
- front/app/components/FacetCard/AddFieldAuto.tsx
- front/app/components/FacetCard/FacetCard.tsx
- front/app/global-styles.ts
Issue #568 
1) made it more clear to the user to type when adding a description within a label
2) made add label card ignore height of sibling cards
> Adressing issue #568

- front/src/components/AuthHeader/UserProfileHeaderButton.tsx
- front/src/components/FacetCard/FacetCard.tsx
- front/src/containers/CrowdPage/AddCrowdLabel.tsx
- front/src/containers/CrowdPage/CrowdPage.tsx
- front/src/containers/StudyPage/StudyPage.tsx
- front/src/containers/StudyPage/components/StarAnimation.tsx
- front/src/containers/StudyPage/components/StudyPageSections/StudyPageSection.tsx
- front/src/containers/StudyPage/components/StudyPageSections/StudyPageSections.tsx
- front/src/containers/TagsPage/TagsPage.tsx
- front/src/containers/WikiPage/WikiPage.tsx
- front/src/containers/WikiPage/components/SubmitAnimation.tsx
- front/src/containers/WorkflowPage/SuggestedLabels.tsx
- front/src/containers/WorkflowPage/WikiSections.tsx
- front/src/containers/WorkflowPage/WorkflowPage.tsx
- front/src/utils/auth.ts
> 559 animation3

- app/services/search_service.rb
Method to create nested agg that filters before going into nested document.
> Nested agg query generation

- front/package.json
- front/src/components/GithubSelector/GithubSelector.tsx
- front/src/components/SlackCounter/SlackCounter.tsx
- front/src/components/SlackCounter/SlackCounterGroup.tsx
- front/src/containers/ProfilePage/EditProfilePage.tsx
- front/src/containers/ProfilePage/ProfilePage.tsx
- front/src/containers/ProfilePage/components/ReviewsTable.tsx
- front/src/containers/StudyPage/StudyPage.tsx
- front/src/containers/StudyPage/components/ReactionsById.tsx
- front/src/containers/StudyPage/components/StudyPageHeader.tsx
- front/src/containers/StudyPage/components/StudyReaction.tsx
- front/src/types/ReactionsById.ts
- front/src/types/StudyReactions.ts
- front/yarn.lock
Takes care of the remaining open items for reactions 
Add icon instead of + 
fix delete reactions
Move placement of reaction selector
Pull all reactions into profile page
Add Sign in modal for reactions when user not signed in
> Experimental reactions

- db/migrate/20200611142633_run_seed_for_reaction_kind.rb
- db/schema.rb
Migration to add in reaction types or remove if the migration is reverted
> Migration to seed

- db/schema.rb
- front/src/containers/AggDropDown/AggDropDown.tsx
- front/src/containers/AggDropDown/BarChart.tsx
- front/src/types/ReactionsById.ts
-Fixes the overflow of the container displaying stuff outside of the container
-Also flips the x/y axis
> Updates to Barchart facet type

- db/schema.rb
- front/src/components/GithubSelector/GithubSelector.tsx
- front/src/components/SlackCounter/SlackCounter.tsx
- front/src/containers/StudyPage/components/StudyPageHeader.tsx
- front/src/types/ReactionsById.ts
- front/src/utils/reactions/reactionKinds.ts
-Centralizes the reaction mapping
-Hides the reaction selector on any click outside the selector container
-Lastly, small refactor to fix reactions not appearing after selecting a reaction
> Reactions Updates

- front/src/components/MultiCrumb/AggCrumb.tsx
- front/src/components/MultiCrumb/ValuesCrumb.tsx
- front/src/containers/AggDropDown/BarChart.tsx
- front/src/containers/SearchPage/Types.ts
- front/src/containers/SearchPage/components/AggFilterInputUpdater.tsx
Adds a breadcrumb for the allow missing field
> 591 allow missing

- app/models/study.rb
- app/services/search_service.rb
- front/src/types/ReactionsById.ts
Added in nesting for reaction to search_data and enabled aggs array
> Reaction nested index

- front/src/containers/ReviewForm/ReviewForm.tsx
@ericharding please make sure that just deleting these values in the defaults doesn't break anything obvious and let's push.
what is really needed is #619 as well as some better handling of the review dimensions in the search and display of studies. This is some thinking and work.
> remove extra dimension in reviews

- app/services/search_service.rb
- front/src/utils/aggs/aggToField.ts
- front/src/utils/constants.ts
- front/src/utils/siteViewUpdater.ts
Changes the query formation of visible options when it is a nested aggregation.
> Code the handle visibility options for nested aggregation.

- app/graphql/types/reaction_kind_type.rb
- app/models/reaction_kind.rb
- db/migrate/20200622173104_add_unicode_reaction_kind.rb
- db/schema.rb
Unicode branch pull request. This branch adds unicode symbols to the database .
> Reaction unicode string

- db/schema.rb
- front/src/containers/FacilitiesPage/FacilitiesPage.tsx
- front/src/containers/Islands/CommonIslands.tsx
- front/src/containers/Islands/FacilityIsland.tsx
- front/src/containers/SearchPage/SearchView.tsx
- front/src/queries/FacilitiesPageQuery.ts
Initial Workings of Issue #639 
To add the component simply add the Facility tag as follows: `<Facility></Facility>`
> Adds Facility page section as an Island renderable by MM component

- front/src/components/SiteForm/SearchForm.tsx
- front/src/containers/SearchPage/SearchView2.tsx
- front/src/containers/SearchPage/Types.ts
This PR takes care of a few of the top priority remaining items for 640:
-Mailmerge Config renders on all views except original table view
-Initial query size has been changed to 100 for the time being 
-Our old table view is back to it's original state.
> RV Components II

- app/graphql/types/crowd_value_type.rb
- app/graphql/types/meta_type.rb
- app/graphql/types/wiki_page_type.rb
- db/schema.rb
Convert meta data from string into graphql types to be able to access key and value attributes
> 649 meta change

- front/src/components/ReactionsBar/GithubSelector/GithubSelector.tsx
- front/src/components/ReactionsBar/SlackCounter/SlackCounter.tsx
- front/src/components/ReactionsBar/index.tsx
- front/src/containers/Islands/BackIsland.tsx
- front/src/containers/Islands/CommonIslands.tsx
- front/src/containers/Islands/FacilityIsland.tsx
- front/src/containers/Islands/NavigationIsland.tsx
- front/src/containers/Islands/ReactionsIsland.tsx
- front/src/containers/Islands/ReviewsIsland.tsx
- front/src/containers/Islands/WikiPageIsland.tsx
- front/src/containers/ReviewsPage/EditReview.tsx
- front/src/containers/ReviewsPage/ReviewsPage.tsx
- front/src/containers/SearchStudyPage/SearchStudyPage.tsx
- front/src/containers/StudyPage/StudyPage.tsx
- front/src/containers/StudyPage/components/StudyPageCounter/StudyPageCounter.tsx
- front/src/containers/StudyPage/components/StudyPageHeader.tsx
- front/src/containers/WikiPage/WikiPage.tsx
- front/src/mutations/ReviewsPageDeleteReviewMutation.ts
- front/src/mutations/WikiPageUpdateContentMutation.ts
- front/src/queries/ReactionKinds.ts
- front/src/queries/ReactionsIslandQuery.ts
- front/src/queries/ReviewPageQuery.ts
- front/src/queries/SearchStudyPageQuery.ts
- front/src/queries/StudyPageQuery.ts
- front/src/queries/WikiPageQuery.ts
- front/src/types/FacilitiesPageQuery.ts
- front/src/types/ReactionsIslandQuery.ts
- front/src/types/ReviewPageQuery.ts
- front/src/types/WikiPageQuery.ts
This should include the remaining islands
-WikiPage
-Navigation
-Back Button
-Reactions
-Reviews
There is still a bug on reaction. There is some work needed around the way the queries are refetched from the Reactions components. I have a fix I am working on but got pulled into a meeting before I could test my solution. 
**WikiPage**
**Reviews**
**Reactions**
**Navigation**
> 639 islands

- app/graphql/types/central_contact_type.rb
- app/graphql/types/overall_official_type.rb
- app/graphql/types/study_type.rb
Willie wants these fields added to the study type to be able to access them.
> added central contact and overall_official fields  to study type

- front/src/components/SiteForm/AggField.tsx
- front/src/components/SiteForm/SearchForm.tsx
- front/src/containers/SearchPage/SearchView2.tsx
- front/src/hooks/useHandlebars.ts
- front/src/utils/aggs/aggToField.ts
This PR handles issues #655 and #675 
First shot shows the UI in factebar
NCT Id in ascending 
NCT Id in descending
> RV components Sort and MM helpers Bug Fix

- db/schema.rb
- docker-compose.yml
Sets elastic password as environment variable instead of plain text password. This will require a environment variable to be added to all servers to make the password work. Also re enabled kibana but using same user and environment password so when you got to kibana you need to log in.
> 671 enviroment variable password

- app/controllers/graphql_controller.rb
- app/graphql/mutations/delete_search_log.rb
- app/graphql/types/mutation_type.rb
- app/graphql/types/query_type.rb
- app/graphql/types/search_log_type.rb
- app/graphql/types/user_type.rb
- app/models/search_log.rb
- app/models/short_link.rb
- app/models/user.rb
- db/migrate/20200805170010_create_search_logs.rb
- db/schema.rb
- spec/models/search_log_spec.rb
Search logging added, including table, model, type, and field in user_type.
> 677 search logging

- app/graphql/types/elastic_study_type.rb
- app/graphql/types/search_result_set_type.rb
- app/models/study.rb
- app/services/search_service.rb
- front/src/containers/SearchPage/SearchView2.tsx
- front/src/types/SearchPageSearchQuery.ts
- front/src/types/StudyItemFragment.ts
Elasticstudytype added to stop using sql on search query.  With new fields added
> 631 search page refactor

- app/graphql/mutations/delete_study_view_log.rb
- app/graphql/types/mutation_type.rb
- app/graphql/types/query_type.rb
- app/graphql/types/study_view_log_type.rb
- app/graphql/types/user_type.rb
- app/models/site_view.rb
- app/models/study.rb
- app/models/study_view_log.rb
- app/models/user.rb
- app/services/search_service.rb
- db/migrate/20200818195416_create_study_view_logs.rb
- db/schema.rb
- front/src/utils/aggs/aggToField.ts
- front/src/utils/constants.ts
This adds in study_view_logs table, The allows users to see the studies they have viewed and delete it from their history, Need front end ui to view and modify logs. It also defaults the facet to a number_range facet.
> 713 714 study view logs

- front/package.json
- front/src/index.tsx
- front/yarn.lock
- [CW-10](https://clinwiki.atlassian.net/browse/CW-10) - Add Fullstory package and initialize it in index.tsx
- Also made sure to add key to environment variables in Heroku
> Add Fullstory package and initialize it in index.tsx

- front/src/index.tsx
Add default `orgId` for Fullstory; should also disable initializing if `orgId` is empty.
> Add default orgId for Fullstory

- front/src/components/AuthHeader/AuthHeader.tsx
Changes the "Donate" button to "Donate to ClinWiki"
> CW-27 change Donate button Text

- front/src/components/MultiCrumb/CrumbWrapper.tsx
- front/src/global-styles.ts
> CW-5 Move breadcrumbs to global styles

- README.md
need to confirm this still works with no values to start in a local set-up, which could require some rails commands to seed instead.
> adding seeding instructions for bulk and workflows

- front/src/containers/Islands/ReviewsIsland.tsx
- front/src/containers/ReviewForm/ReviewForm.tsx
- front/src/containers/ReviewsPage/EditReview.tsx
- front/src/containers/ReviewsPage/ReviewsPage.tsx
- front/src/containers/WorkflowPage/WorkflowPage.tsx
Adds a cancel button to review form so user can close out after clicking the "Write Review" button.
> CW-26 Adds cancel button to Reviews Form

- front/src/components/MailMerge/MMTestComponent.tsx
- front/src/components/MailMerge/MailMergeView.tsx
- front/src/components/MailMerge/SchemaSelector.tsx
- front/src/components/SiteForm/PageForm.tsx
- front/src/containers/GenericPage/GenericPage.tsx
- front/src/containers/Islands/CommonIslands.tsx
Reverts clinwiki-org/clinwiki#779
Looks like there is an issue when we try to edit the ALS site so something in this commit must have made it incompatible with configuration in that one. 
@ericharding Can you please take a look at the config [here](http://staging.clinwiki.org/sites/7/edit/page) to see what it may have been?
> Revert "Island <Expander> control"

- front/src/components/MailMerge/MMTestComponent.tsx
- front/src/components/MailMerge/MailMergeView.tsx
- front/src/components/MailMerge/SchemaSelector.tsx
- front/src/components/SiteForm/PageForm.tsx
- front/src/containers/GenericPage/GenericPage.tsx
- front/src/containers/Islands/CommonIslands.tsx
Reverts clinwiki-org/clinwiki#781
@ericharding verified the issue is specific to commit b3ed39e1 so I'm going to revert this revert and just undo that one commit.
> Revert "Revert "Island <Expander> control""

- front/src/components/MailMerge/MailMergeView.tsx
Manually undo changes from commit b3ed39e1 per Eric's recommendation to fix issue with queryString (broke ALS edit page functionality).
> Manually undo changes from commit b3ed39e1 per Eric's recommendation

- front/src/containers/SearchPage/SearchPage.tsx
- front/src/containers/SearchPage/SearchView2.tsx
- front/src/containers/SearchPage/components/CrumbsBar.tsx
- Add spacing back in between sort drop down and breadcrumbs bar
- Move `Bulk Update` button next to `Export` button
> Fix spacing and move `Bulk Update` button

- front/src/components/Edits/Edit.tsx
- front/src/components/Edits/EditBlurb.tsx
- front/src/components/Edits/Edits.tsx
- front/src/components/Edits/ExpandedEdit/ExpandedAsRawDiff.tsx
- front/src/components/Edits/ExpandedEdit/ExpandedEdit.tsx
- front/src/components/Edits/ExpandedEdit/FrontMatterExpandedEdit.tsx
- front/src/components/Edits/ExpandedEdit/WikiExpandedEdit.tsx
- front/src/containers/Islands/WikiPageIsland.tsx
Reverts clinwiki-org/clinwiki#785
Having some issues getting this working in staging. Also realized the requirement is to have this as a separate island.
> Revert "CW-17 - Bring back history button"

- front/src/components/Edits/Edit.tsx
- front/src/components/Edits/EditBlurb.tsx
- front/src/components/Edits/Edits.tsx
- front/src/components/Edits/ExpandedEdit/ExpandedAsRawDiff.tsx
- front/src/components/Edits/ExpandedEdit/ExpandedEdit.tsx
- front/src/components/Edits/ExpandedEdit/FrontMatterExpandedEdit.tsx
- front/src/components/Edits/ExpandedEdit/WikiExpandedEdit.tsx
- front/src/containers/Islands/WikiPageIsland.tsx
Reverts clinwiki-org/clinwiki#789
> Revert "Revert "CW-17 - Bring back history button""

- app/graphql/mutations/create_site.rb
- app/graphql/mutations/update_site.rb
- app/graphql/types/site_type.rb
- db/migrate/20200924190849_add_hide_donation_to_site.rb
- db/schema.rb
- front/src/components/AuthHeader/AuthHeader.tsx
- front/src/components/AuthHeader/UserProfileHeaderButton.tsx
- front/src/components/SiteForm/MainForm.tsx
- front/src/components/SiteForm/SiteForm.tsx
- front/src/containers/SiteProvider/SiteProvider.tsx
- front/src/types/AdminViewsProviderQuery.ts
- front/src/types/CreateSiteMutation.ts
- front/src/types/SiteFragment.ts
- front/src/types/SiteProviderQuery.ts
- front/src/types/UpdateSiteMutation.ts
- front/src/types/globalTypes.ts
Adds configuration at the site level on whether the donate button is displayed or hidden in the Navigation Bar
> CW-70 Hide 'Donate to Clinwiki' Button

- front/src/containers/GenericPage/GenericPage.tsx
- front/src/containers/SearchPage/SearchPage.tsx
small bug in our default pageView logic and updated a few routes to use the querystringAll function vs hardcoding the link
> small bug fix in our default pageView logic

- front/src/containers/GenericPage/GenericPage.tsx
- front/src/containers/SearchPage/SearchPage.tsx
Reverts clinwiki-org/clinwiki#799
> Revert "small bug fix in our default pageView logic"

- front/src/containers/SearchPage/SearchPage.tsx
Reverts clinwiki-org/clinwiki#798
reversing 3 merges to remove facet issue
> Revert "CW-55-handles q coming from home.clinwiki"

- front/src/containers/SearchPage/SearchPage.tsx
Reverts clinwiki-org/clinwiki#797
reversing facet issue
> Revert "CW-74- makes facet bar collapsible"

- front/src/containers/SearchPage/SearchPage.tsx
Reverts clinwiki-org/clinwiki#801
> Revert "Revert "CW-55-handles q coming from home.clinwiki""

- front/src/containers/SearchPage/SearchPage.tsx
- front/src/containers/SearchPage/SearchView.tsx
- front/src/containers/SearchPage/SearchView2.tsx
- front/src/types/SearchPageSearchQuery.ts
Reduces the default SearchPageSearchQuery on my machine from 199kb to 187kb.  Will definitely be more pronounced on staging b/c I don't have any crowd aggs.
> Reduce over-request in SearchPageSearchQuery

- front/src/components/StyledComponents/index.ts
- front/src/containers/Islands/BackIsland.tsx
- front/src/containers/SearchPage/SearchPage.tsx
- front/src/containers/SearchPage/SearchView2.tsx
- front/src/containers/SearchPage/components/ExportToCsvButton.tsx
- front/src/containers/StudyPage/components/StudyPageHeader.tsx
CW-82 change the back button to "Search Results"
CW-83 Duplicates the presearch button to top of presearch
CW-84 changes export button to download icon only, adds slight scale to buttons on hover for improved ui feedback
> CW-82 CW-83 CW-84  Ui changes

- front/src/containers/SearchPage/SearchPage.tsx
> include collapsible in same conditional as facetbar

- front/src/containers/CurrentUser/CurrentUser.tsx
- front/src/containers/Islands/WikiPageIsland.tsx
- front/src/containers/Islands/WorkflowIsland.tsx
- front/src/containers/StudyPage/components/StarAnimation.tsx
Adds animation to the new Island Components (Specifically WikiPage and Workflow)
> CW-65-animation patch

- front/src/containers/SearchPage/SearchPage.tsx
- front/src/containers/SearchPage/SearchView2.tsx
- front/src/containers/SearchPage/components/TableRV.tsx
> CW-91 add link to study page on row click of table

- front/src/containers/Islands/WikiPageIsland.tsx
- front/src/containers/Islands/WorkflowIsland.tsx
- front/src/containers/StudyPage/components/StarAnimation.tsx
Changes star color to configured button color, additionally makes the animation larger
> CW-90 change animation star color 

- front/src/containers/SearchPage/components/Aggs.tsx
> removing console log

- front/src/components/MailMerge/MailMergeHelpers.ts
- front/src/components/MailMerge/MailMergeView.tsx
- front/src/global-styles.ts
Initial working of a few added MailMerge helper functions. See screenshot for implementation example 
This is still kind of a WIP as I noticed some weird bugs with placement on the FindAndReplace function, sometimes the template will error if there is no parent html element in the MM configuration.
> CW-87  first wave of mm functions 

- app/services/search_service.rb
- config/puma.rb
Fixed a config from config/puma that was still set for diagnostics.
> aggs now filtering results correctly

- app/services/search_service.rb
- app/services/study_edge_service.rb
added a method search_without_aggs to searvice_search.rb
> working locally, load times less than half

- app/graphql/types/site_agg_field_type.rb
- app/models/site_view.rb
- front/src/components/SiteForm/AggField.tsx
- front/src/containers/AggDropDown/AggDropDown.tsx
- front/src/containers/PresentSiteProvider/PresentSiteProvider.tsx
- front/src/containers/SiteProvider/SiteProvider.tsx
Adds a checkbox to show/hide the Filter Toolbar and Allow missing.
> adds the config outlined in CW-127 and CW-128

- front/src/containers/Islands/WikiPageIsland.tsx
This PR handles a few of the Workflow edit tickets ( CW-125 and CW-126)
> Wiki page edits edit flow update

- front/src/containers/BulkEditPage/BulkEditPage.tsx
changed to 1000, should decrease performance but acceptable for admin bulk function
> temp fix for bulk visible options not working

- app/graphql/clinwiki_schema.rb
- app/graphql/types/site_agg_field_type.rb
- app/models/site_view.rb
- front/src/components/SiteForm/AggField.tsx
- front/src/containers/PresentSiteProvider/PresentSiteProvider.tsx
- front/src/containers/SiteProvider/SiteProvider.tsx
- front/src/types/CopySiteViewMutation.ts
- front/src/types/CreateSiteMutation.ts
- front/src/types/CreateSiteViewMutation.ts
- front/src/types/PresentSiteFragment.ts
- front/src/types/PresentSiteProviderQuery.ts
- front/src/types/SiteFragment.ts
- front/src/types/SiteProviderQuery.ts
- front/src/types/SiteViewFragment.ts
- front/src/types/UpdateSiteMutation.ts
- front/src/types/UpdateSiteViewMutation.ts
Adds AggSublabel to aggs & siteview config
Increased gql max query complexity from 500 to 600
> CW-151 AggSublabel

- app/graphql/types/site_agg_field_type.rb
- app/models/site_view.rb
- front/src/components/SiteForm/AggField.tsx
- front/src/containers/PresentSiteProvider/PresentSiteProvider.tsx
- front/src/containers/SiteProvider/SiteProvider.tsx
- front/src/types/CopySiteViewMutation.ts
- front/src/types/CreateSiteMutation.ts
- front/src/types/CreateSiteViewMutation.ts
- front/src/types/PresentSiteFragment.ts
- front/src/types/PresentSiteProviderQuery.ts
- front/src/types/SiteFragment.ts
- front/src/types/SiteProviderQuery.ts
- front/src/types/SiteViewFragment.ts
- front/src/types/UpdateSiteMutation.ts
- front/src/types/UpdateSiteViewMutation.ts
Adds defaultToOpen field to backend and checkbox to each agg in site view config
> CW-152 Adds DefaultToOpen

- app/graphql/mutations/create_saved_search.rb
Adds crowd_aggs consideration into the build name label method
> CW-182-SaveSearchBug on crowd_aggs patch

- front/src/containers/SearchPage/components/CrumbsBar.tsx
- front/src/containers/SearchPage/components/SaveSearch.tsx
Relocates save search button to left of "download" button and icon changed to a bookmark
> CW-180-SaveSearchButton relocated and icon change

- front/src/components/LabeledButton/LabeledButton.tsx
- front/src/components/LabeledButton/index.tsx
- front/src/containers/ProfilePage/components/UserSavedSearches.tsx
- front/src/containers/SearchPage/components/CrumbsBar.tsx
- front/src/containers/SearchPage/components/ExportToCsvButton.tsx
- front/src/containers/SearchPage/components/SaveSearch.tsx
Adds new LabeledButton component,
Adds labels 5 buttons: save, search, download csv, Search term, delete saved search and navigate to link
> CW-181 Adds Buttons Helper Label

- front/src/containers/ProfilePage/components/UserSavedSearches.tsx
makes saved search names into links
> CW-189- Hyperlink saved search names

- app/graphql/types/elastic_study_type.rb
- app/graphql/types/study_type.rb
- front/src/components/SiteForm/PagesForm.tsx
- front/src/components/StudySummary/StudySummary.tsx
- front/src/containers/SearchPage/SearchView2.tsx
> CW-161 StudyViewCount accessible through MM

- front/src/containers/SearchPage/SearchPage.tsx
Added page names that show up for front end based on current params.
> front-end page names

- app/graphql/mutations/create_saved_search.rb
- app/graphql/types/saved_search_type.rb
- app/models/saved_search.rb
- db/migrate/20201202195235_add_url_to_saved_search.rb
- db/schema.rb
Backend files missed in the original PR
#871
> SavedSearch update

- Rakefile
- app/helpers/wiki_helper.rb
fixing some things ahead in master
> bulk and import fixes

- Rakefile
- app/helpers/wiki_helper.rb
fixing some things ahead in master
> bulk and import/export updates to staging

- Rakefile
use email submitted in import file instead of hard coded bot.
also removed old references to "tags" which is now just any other type of crowd value
> change import to use email

- front/src/containers/SearchPage/SearchPage.tsx
- front/src/containers/SearchPage/SearchView2.tsx
SearchView holds our SearchPageSearch query. And now that no other component is dependent on that query we can conditionally render it from our SearchPage component
> CW-214 conditionally render SearchView

- imports/tag_cleanup_20201206.csv
Reverts clinwiki-org/clinwiki#885
> Revert "update to import file"

- app/graphql/mutations/create_saved_search.rb
- app/graphql/types/query_type.rb
Considers greater/less than ranges and location radius/zipcode for naming,
(in both -naming SearchLog and -naming for SavedSearches)
Removes limit of 5 search terms in naming
> WIP: CW-213 Naming adds missing values

- app/graphql/mutations/create_study_view_log.rb
- app/graphql/types/mutation_type.rb
- app/graphql/types/query_type.rb
- front/src/containers/GenericPage/GenericPage.tsx
- front/src/queries/StudyViewLogMutation.ts
> fixes log creation running on every re-render

- front/src/containers/SearchPage/SearchPage.tsx
> Move lonely function back with its friends

- front/src/containers/SearchPage/SearchPage.tsx
- front/src/queries/SearchPageSearchQuery.ts
Takes care of CW-223 with Doc counts load
> [Fix for] queries running with no aggFilters prematurely

- front/src/containers/GenericPage/GenericPage.tsx
- front/src/containers/Islands/WorkflowIsland.tsx
- front/src/containers/WorkflowPage/SuggestedLabels.tsx
Reverts clinwiki-org/clinwiki#901
> Revert "Persist unchanged data during reload using previousData"

- app/graphql/types/site_agg_field_type.rb
- app/models/site_view.rb
- front/src/components/SiteForm/AggField.tsx
- front/src/containers/SiteProvider/SiteProvider.tsx
- front/src/queries/PresentSiteProviderQuery.ts
configure Dropdown to default start as open/closed , 
adds backend fields and front end queries, and config to admin panel
> CW-237 CW-232 dropdown default to open?

- front/src/containers/AggDropDown/customDrop.stories.tsx
- front/src/stories/Button.stories.tsx
- front/src/stories/Header.stories.tsx
- front/src/stories/Page.stories.tsx
remove dependency to storybook/react/types-6-0 and change to just storybook/react
> Storybook types

- front/src/containers/AggDropDown/customDrop.stories.tsx
- front/src/stories/Button.stories.tsx
- front/src/stories/Header.stories.tsx
- front/src/stories/Page.stories.tsx
Reverts clinwiki-org/clinwiki#917
> Revert "Storybook types"

- front/src/containers/ThemeProvider/ThemeProvider.tsx
- front/src/global-styles.ts
> Crumbs color add

- .vscode/settings.json
- app/models/wiki_page.rb
- front/src/containers/AggDropDown/AggDropDown.tsx
- front/src/containers/AggDropDown/AggKeyValuePairsDropDown.tsx
- front/src/containers/AggDropDown/AllowMissingDropDownItem.tsx
- front/src/containers/AggDropDown/CustomDrop.tsx
- front/src/containers/AggDropDown/CustomDropCrumbs.tsx
- front/src/containers/AggDropDown/CustomDropPanel.tsx
- front/src/containers/ThemeProvider/ThemeProvider.tsx
- front/src/global-styles.ts
- front/src/queries/SearchPageCrowdAggBucketsQuery.ts
- front/src/services/search/actions.ts
- front/src/services/search/api.ts
- front/src/services/search/queries.ts
- front/src/services/search/reducer.ts
- front/src/services/search/sagas.ts
- front/src/services/search/types.ts
- front/src/types/SearchPageCrowdAggBucketsQuery.ts
Redux SearchPage Agg and Crow Agg Buckets Queries 
Implemented on AggDropDown and AggKeyValuePairsDropDown,
bug added to Jira after redux on search page in presearch when bucket is checked it refreshes component 
Includes latest bug fixes from staging merge.
> CW-273 Redux sp buckets w staging

- front/src/components/MailMerge/MMTestComponent.tsx
- front/src/components/MailMerge/MailMergeFormControl.tsx
- front/src/components/SiteForm/SearchTemplate.tsx
- front/src/containers/SearchPage/components/StudyFragmentQueryComponent.tsx
- front/src/queries/IntrospectionQuery.ts
- front/src/reducers.ts
- front/src/sagas.ts
- front/src/services/introspection/actions.ts
- front/src/services/introspection/api.ts
- front/src/services/introspection/reducer.ts
- front/src/services/introspection/sagas.ts
- front/src/services/introspection/types.ts
Redux Introspection query implemented on 
MailMergeFormControl.tsx, MMTestComponent.tsx, SearchTemplate.tsx
> CW-272 Redux introspection query

- front/src/containers/AggDropDown/AggDropDown.tsx
- front/src/containers/AggDropDown/AggKeyValuePairsDropDown.tsx
- front/src/containers/SearchPage/components/SaveSearch.tsx
- front/src/services/search/sagas.ts
Implement redux and remove all apollo from component, 
clean up console logs around
> Redux AggKeyValuePairDropDown

- front/src/containers/SearchPage/components/SaveSearch.tsx
temporary message to default subscribe weekly updates for saved searches until we give UI choices for whether to subscribe or other choices. Future would be an opt-in (or out) "subscribe" checkbox or interface with options like weekly or type of update
> add subscribed search message

- front/src/components/AuthHeader/AuthHeader.tsx
> fixing links in header

- api/undefined/info.log
- front/src/containers/LoginPage/SignInPage.tsx
- front/src/containers/LoginPage/SignUpPage.tsx
- front/src/services/user/actions.ts
- front/src/services/user/reducer.ts
- front/src/services/user/sagas.ts
- front/src/services/user/types.ts
Hotfix for master, 
Error messages added for signup/signin errors. 
Autosign in working - currently redirects to last page (which isn't great if it was signgin) 
shoudl fix further in node though as it's a very minor headache.
> Hotfix signup 

- api/config.js
- api/package-lock.json
- api/package.json
- api/src/pipeline/jobs/aact.job.js
- api/src/pipeline/jobs/clinwiki.job.js
- api/src/pipeline/jobs/reindex.job.js
- api/src/pipeline/pipeline.queue.js
- api/src/pipeline/scheduler.js
- api/src/pipeline/worker.js
- api/src/search/elastic.js
- api/src/util/db.js
- docker-compose.yml
Added queued ES imports for base study table and wiki text. Added data-pipeline to docker.
> Queued import of base study table and wiki page updates

- front/src/components/SiteForm/PageForm.tsx
- front/src/components/SiteForm/PagesForm.tsx
- front/src/services/study/actions.ts
- front/src/services/study/api.ts
- front/src/services/study/mutations.ts
- front/src/services/study/queries.ts
- front/src/services/study/reducer.ts
- front/src/services/study/sagas.ts
- front/src/services/study/types.ts
- front/src/utils/graphqlUtil.ts
adds hasura page view query boilerplate,
create, delete, update pv mutations boilerplate
> PageViews fetching from Hasura,

- api/config.js
- api/src/users/user.manager.js
- front/.prettierrc
- front/src/components/MailMerge/MailMerge.tsx
- front/src/components/SiteForm/PageForm.tsx
- front/src/components/WikiPageEditor/WikiPageEditor.tsx
- front/src/containers/FacilitiesPage/FacilityCard.tsx
- front/src/containers/Islands/FacilityIsland.tsx
- front/src/containers/Islands/WikiPageIsland.tsx
- front/src/services/introspection/api.ts
- front/src/services/study/actions.ts
- front/src/services/study/api.ts
- front/src/services/study/mutations.ts
- front/src/services/study/queries.ts
- front/src/services/study/reducer.ts
- front/src/services/study/sagas.ts
- front/src/services/study/types.ts
- front/src/utils/graphqlUtil.ts
Using new Hasura console ctgov-exp-x 
Fetching Hasura Faciliites, Wiki Page & Page Views.
Fixes for wiki page bugs.
> Dhd ctgov exp wiki page , facilities, page views Hasura

- api/schema.graphql
- api/src/pipeline/jobs/clinwiki.triggers.js
- api/src/search/elastic.js
- api/src/search/search.manager.js
- Update clinwiki triggers to include fm_
- Fix for snake case/camelCase mismatch
> Node search params

- front/src/components/MailMerge/MailMergeView.tsx
- front/src/containers/GenericPage/GenericPageChild.tsx
- front/src/containers/Islands/CommonIslands.tsx
- front/src/containers/ProfilePage/components/UserSavedSearches.tsx
- front/src/services/search/sagas.ts
- front/src/services/site/sagas.ts
- front/src/services/study/sagas.ts
replaces study with hasura studies for study route
> Hasura studies replacing study route

- front/src/containers/App/App.tsx
- front/src/containers/GenericPage/GenericPageWrapper.tsx
on app load reroute to default search page, no landing page
> CW-413 route to default search on start

- front/src/services/search/api.ts
- front/src/services/search/mutations.ts
- front/src/services/search/queries.ts
- front/src/services/search/sagas.ts
Recover/get  short link id (as Rails was doing) to send in with saved searches create  to avoid notify app changes
> CW-425  Recover short link id in saved searches

- Gemfile
- Gemfile.lock
- api/src/pipeline/jobs/geocode.job.js
- api/src/search/search.manager.js
- api/src/search/search.resolver.js
- compose/Dockerfile
- compose/nginx/default.conf
- db/schema.rb
- docker-compose.yml
- front/apollo.config.js
- front/package.json
Also commented out clinwiki container but left in the docker-compose.yml in the event we need to reindex locally. 
Running locally. Want to have @rodctech or @bespinosa01 test locally before we merge into develop.
> removed apollo and made ngnix changes

- api/src/search/search.manager.js
- front/src/components/MailMerge/HasuraMailMergeFormControl.tsx
- front/src/components/MailMerge/MailMergeFormControl.tsx
- front/src/components/MailMerge/SchemaSelector.tsx
- front/src/services/introspection/actions.ts
- front/src/services/introspection/api.ts
- front/src/services/introspection/reducer.ts
- front/src/services/introspection/sagas.ts
- front/src/services/introspection/types.ts
- front/src/services/search/sagas.ts
- front/src/services/study/actions.ts
- front/src/services/study/api.ts
- front/src/services/study/queries.ts
- front/src/services/study/sagas.ts
- front/src/services/study/types.ts
Fix for admin for Page Views. 
SEARCH:
STUDY:
> Pageview query failure

- front/src/containers/Islands/IslandAggChild.tsx
useEffect with handleLoadMore being called unnecessarily. Still had to be called in the sorts toggle.
> Fix for #1015, removed unecessary hlm in useEffect

- front/src/containers/AggDropDown/CustomDropPanel.tsx
- front/src/containers/Islands/WfIslandAggChild.tsx
- front/src/containers/Islands/WfIslandAggWrappper.tsx
- front/src/services/crowdKeys/actions.ts
- front/src/services/crowdKeys/api.ts
- front/src/services/crowdKeys/mutations.ts
- front/src/services/crowdKeys/reducer.ts
- front/src/services/crowdKeys/sagas.ts
- front/src/services/crowdKeys/types.ts
- front/src/services/study/queries.ts
Adds Crowd Title text box editor Island
> Wf Crowd Titles Island Text 

- front/src/containers/AggDropDown/CustomDrop.tsx
- front/src/containers/AggDropDown/CustomDropPanel.tsx
- front/src/services/search/reducer.ts
new placeholder
disable data while filtering
> Fastest loading state

- front/src/components/MailMerge/HasuraMMFragment.ts
- front/src/components/MailMerge/MMTestComponent.tsx
- front/src/components/MailMerge/MailMerge.tsx
- front/src/components/MailMerge/MailMergeHelpers.ts
- front/src/components/MailMerge/MailMergeView.tsx
`{{ $Reduce arrayOfValuesToReduce  }}` : Combines all crowd_values of the same crowd_key in an array. Result is a reduced array of crowd_keys and values.   
**Input:**
**Output:**
**Sample Implementation**
You can use the `if` helper to conditionally render a block. If its argument returns `false`, `undefined`,`null`,`""`, `0`, or `[]`, Handlebars will not render the block.
`runConditional( value1, operator, value2 )` : 
compares value1 to value 2 based on possible operator values (`==`, `>`, `<` ) ; If neither is given defaults to "==";
returns boolean. 
runConditional is perfect to be used alongside `{{#if}}{{else}}{{/if}}`
**Input:**
**Output:**
**Implementation**
> Additional MM helpers

- front/src/components/ProtectedRoute/ProtectedRoute.tsx
- front/src/components/ProtectedRoute/Unauthorized.tsx
- front/src/containers/AggDropDown/InputFilter.tsx
- front/src/containers/App/App.tsx
- front/src/containers/EditAggIslandsPage/EditAggIslandsPage.tsx
- front/src/containers/Islands/StudyInfiniteScroll.tsx
- front/src/containers/Reindex/index.tsx
- front/src/containers/SitesPage/SitesPage.tsx
Move the Close Live Search button up before results
> Closing search bar

- front/src/containers/AggDropDown/InputFilter.tsx
- front/src/global-styles.ts
> implement mobile friendly search bar

- front/src/components/MailMerge/MailMergeView.tsx
- front/src/containers/EditAggIslandsPage/EditAggIslandsPage.tsx
- front/src/containers/Islands/IslandAggWrappper.tsx
- front/src/containers/Islands/WfIslandAggWrappper.tsx
- front/src/services/search/actions.ts
- front/src/services/search/api.ts
- front/src/services/search/queries.ts
- front/src/services/search/reducer.ts
- front/src/services/search/sagas.ts
- front/src/services/search/types.ts
Changes the way we query island_config. Instead of querying all it takes in an idList of configs to fetch. We already find these in our MMView so just leveraged those idArrays for our request,
> Island config fetch

- front/src/containers/Islands/ResultSort.tsx
- front/src/global-styles.ts
> display current sort selection in Dropdown

- front/src/components/LabeledButton/LabeledButton.tsx
- front/src/containers/AggDropDown/LocationAgg.tsx
- front/src/containers/Islands/SearchWithin.tsx
- front/src/containers/SearchPage/components/SaveSearch.tsx
> update button tittle for some labeledButton

- api/src/search/translator.js
> add Wildcard results into search query

- api/schema.graphql
- api/src/admin/admin.resolver.js
- api/src/pipeline/jobs/indexDoc.job.js
- api/src/pipeline/scheduler.js
- front/src/containers/Reindex/index.tsx
- front/src/services/admin/actions.ts
- front/src/services/admin/api.ts
- front/src/services/admin/queries.ts
- front/src/services/admin/sagas.ts
- front/src/services/admin/types.ts
- Adds UI for re-indexing by date. 
If no date specified defaults to yesterdays date. 
- Runs reindex by date job nightly instead of old aact reindex
> Reindex by date
