- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- app/models/reindexes_study.rb
- app/models/study.rb
- app/workers/aact_sync.rb
- app/workers/process_queue_job.rb
- config/initializers/searchkick.rb
- config/initializers/sidekiq.rb
- config/schedule.yml
* Adds sidekiq cron functionality
* Improves reindexing by implementing a batch background indexer.
This makes queries against all tables in in batches of ids,
using fewer queries and less time in total for all queries.
* Add tooling for synchronizing with AACT over N previous days
* Add sidekiq cron worker to reindex nightly over the last day
> Add support for nightly indexing (resolves #50)

- app/graphql/types/date_time_type.rb
- config/initializers/time_formats.rb
This is just a stopgap for #184, because right now apollo-client has no way to serialize custom scalars. I had hoped to find a client alternative to https://github.com/apollographql/graphql-tools/blob/master/docs/source/scalars.md#date-as-a-scalar, but there is none.
Ideally they will implement it before we need to make a better solution, but I'm not holding my breath because the issue has been open since 2016 (see: https://github.com/apollographql/apollo-client/issues/585, further discussion at: https://github.com/apollographql/apollo-feature-requests/issues/2).
If not, there are some unofficial alternatives to look into such as https://github.com/cult-of-coders/apollo-client-transformers.
> Fix date format

- app/graphql/types/public_user_type.rb
- app/graphql/types/query_type.rb
Public user type to restrict data the query can get back for public profiles
> Public user type for user query, only first and last name

- front/app/containers/App/App.tsx
- front/app/containers/BulkEditPage/BulkEditPage.tsx
- front/app/containers/SearchPage/SearchPage.tsx
- front/app/containers/WorkflowPage/WorkflowPage.tsx
Both WorkflowPage and BulkEditPage previously read the hash from math.params, but with new routing no longer the case. This makes necessary updates to correctly read hash.
> RTM resolves issue #415 and #414 

- front/app/containers/SearchPage/components/AggFilterInputUpdater.tsx
First picture shows we have the crowdAgg _tags_ to be displayed as number range 
Shows number range with a min value selected, no error
> RTM Resolves issue where crowdAggs would error out Range Filter 

- front/app/components/Edits/Edit.tsx
- front/app/components/Edits/EditBlurb.tsx
- front/app/components/Edits/Edits.tsx
- front/app/components/Edits/ExpandedEdit/ExpandedAsRawDiff.tsx
- front/app/components/Edits/ExpandedEdit/ExpandedEdit.tsx
- front/app/components/Edits/ExpandedEdit/FrontMatterExpandedEdit.tsx
- front/app/components/Edits/ExpandedEdit/WikiExpandedEdit.tsx
- front/app/components/Edits/ExpandedEdit/index.tsx
- front/app/components/Edits/StyleWrapper.tsx
- front/app/components/Edits/WikiPageEditFragment.tsx
- front/app/components/Edits/index.ts
- front/app/containers/CrowdPage/CrowdPage.tsx
- front/app/containers/TagsPage/TagsPage.tsx
- front/app/containers/WikiPage/WikiPage.tsx
Related to #166 .
Display a blurb for a given change, with a more configurable UI for crowd annotation changes vs. wiki changes.
> 166 wiki history ui

- Gemfile
- Gemfile.lock
- app/graphql/mutations/update_wiki_content.rb
- app/graphql/mutations/upsert_wiki_label.rb
- app/models/wiki_page.rb
- spec/factories/wiki_page.rb
- spec/fixtures/files/graphql/wiki_page_mutations/update_wiki_content.gql
- spec/fixtures/files/graphql/wiki_page_mutations/upsert_wiki_label.gql
- spec/graphql/update_wiki_content_spec.rb
- spec/graphql/upsert_wiki_label_spec.rb
- spec/graphql/wiki_page_edit_history_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
* Utilize ActiveRecord-idiomatic approach for solving associations for two models that are being instantiated at the same time (this was the source of the bug; we've been creating edits with `nil` `wiki_page_id`s)
* Introduce `database_cleaning` gem for improved isolation of tests (we'll need to think about how to figure out what to do with performance, but the default transaction configuration was starting to break more advanced tests)
* Add a couple of graphql tests to validate the core mutations working with `WikiPage` objects are  being changed properly, with the correct values for edit history
Resolves #241
> Ensure an initial edit is created for wiki pages

- CONTRIBUTING.md
- app/models/wiki_page.rb
- config/environments/test.rb
- front/app/components/Edits/EditBlurb.tsx
- front/app/components/Edits/ExpandedEdit/ExpandedEdit.tsx
- front/app/components/Edits/ExpandedEdit/FrontMatterExpandedEdit.tsx
- front/app/components/Edits/ExpandedEdit/WikiExpandedEdit.tsx
- front/app/types/CrowdPageDeleteWikiLabelMutation.ts
- front/app/types/CrowdPageUpsertWikiLabelMutation.ts
- front/app/types/StudyPagePrefetchQuery.ts
- front/app/types/TagsPageAddWikiTagMutation.ts
- front/app/types/TagsPageDeleteWikiTagMutation.ts
- front/app/types/WikiPageEditFragment.ts
- front/app/types/WikiPageFragment.ts
- front/app/types/WikiPageQuery.ts
- front/app/types/WikiPageUpdateContentMutation.ts
- front/app/types/globalTypes.ts
It looks like merging the fix for creating a wiki edit on the first edit may have broken some things about the new wiki edit UI.
I also noticed that running tests now truncates your dev database. Whoops! I've fixed that in this PR.
There also appear to be some miscellaneous types that needed re-adding.
> misc bug-fixes post double wiki edit merge

- front/app/containers/SearchPage/SearchPage.tsx
Previously terms coming from the url query string would override any preselected options in the site view. 
Moved the previously written functions into the updateStateFromHash to update the params with the query alongside when it updates the params from ParamsQueryComponent
In following Screenshot I have configured my siteview to have the mesh term _coronavirus infections_
This is the view with no query string
The screen recording shows when adding a query string to url it it will add the query string to the breadcrumbs once the new hash loads
> RTM Resolves issue #420: Better handles serach query string 

- front/app/containers/AggDropDown/AggDropDown.tsx
Presearch crowd aggs previously were not getting it's default sort options from the right place. 
The first picture is of the configuration I set for presearch followed by facet bar. I included both so you can see I have essentially configured them to be opposites to show they are now independent as was intended. 
_Preseach Config_
_FacetBar Config_
Lastly, this image shows the presearch correctly displaying configured default sort options with the _tags_ open in the facet bar to demonstrate they are different.
> RTM Additional fix for issue #372

- front/app/containers/BulkEditPage/BulkEditView.tsx
- front/app/containers/SearchPage/components/AggFilterInputUpdater.tsx
- front/app/containers/WorkflowPage/SuggestedLabels.tsx
- front/app/utils/aggs/bucketKeyIsMissing.ts
* Fix a bug where you couldn't select "allow missing" for pre-search view site config
* Don't show missing value as an option for a bulk label
* Don't show the missing value as a suggested label in workflow (I had a hard time getting this to display on my local instance, so I just found where it was in the code)
(resolves #441)
> Fix workflow and bulk update facet display of missing values 

- app/graphql/types/diff_type.rb
- app/graphql/types/wiki_page_edit_type.rb
* Added `DIFFCOMMENT` to GraphQL Enum
* Replace `diff-comment` status with `DIFFCOMMENT` status during preparation of data in GraphQL backend
Since Diffy uses the native `diff` command on a given deployment to work, I'm wondering if this didn't get caught earlier because of differences in the `diff` binary as deployed vs. on my Mac.
Another thing worth noting: I parsed all of our existing diff html entries using Nokogiri, and it took me about 20 seconds to parse all existing records, so I think that answers that in terms of performance for individual entries.
> fix diff comment bug in new history view

- front/app/containers/FacilitiesPage/FacilityCard.tsx
A component was missing withTheme Provider causing some studies (specifical ones with facility contact Info) to crash when expanding facilities card
> RTM Missing themeProvider component: issue #484

- front/app/components/Edits/Edit.tsx
- front/app/components/Edits/Edits.tsx
- front/app/containers/WikiPage/ExpansionContext.tsx
- front/app/containers/WikiPage/WikiPage.tsx
* Move management of "expanded" vs "not expanded" view of an edit to `WikiPage` container, inside of an `ExpansionContext`
* Add ability to maximize all history via a button rendered in the wiki page container
* Add ability to minimize all history via a button rendered in the wiki page container
* Utilize the expansion context to provide a view of whether a given edit should or should not render details.
> add buttons to maximize and minimize all edits on history page

- app/graphql/mutations/sign_in.rb
Fix where you could bypass authorization without correct password. Sign in now has two ways you can go. One is if you pass a o_auth_token that is not empty(currently empty always from front end unless oauth picked) you go through the google oauth. If you pass an empty string oauthtoken or no oauthtoken you go through the password path.
> 494 bug fix google oauth

- front/app/components/StyledComponents/index.ts
- front/app/containers/AggDropDown/Buckets.tsx
- front/app/containers/LoginPage/SignInPage.tsx
- front/app/containers/WorkflowPage/SuggestedLabels.tsx
- front/app/types/SuggestedLabelsQuery.ts
* Filter missing values from the workflow panel properly
* Noticed that some bucket values should be getting
rendered with `keyAsString` instead of `key`, so
added some support there.
I already fixed this once, but I saw that the login form
button was turned back into a div. *This breaks logging
in through submitting by a carriage return. Usability is important!*
I've changed the `ThemedButton` from a styled div to a styled
button.
> Workflow missing value bugfixes

- app/models/search_export.rb
- app/services/search_service.rb
- spec/graphql/__snapshots__/basic_agg_filter_search_graphql_response.snap
- spec/graphql/__snapshots__/basic_agg_filter_search_query.snap
- spec/graphql/__snapshots__/basic_search_graphql_response.snap
- spec/graphql/__snapshots__/basic_search_query.snap
- spec/graphql/__snapshots__/range_filter_search_graphql_response.snap
- spec/graphql/__snapshots__/range_filter_search_query.snap
- spec/models/search_export_spec.rb
`SearchExport#params`, which we rely on for passing the expect parameters to the search service, was passing the parsed JSON, which had keys that were strings, and not symbols. We use `deep_symbolize_keys!` to enforce the expected behavior for interacting with the agg filters.
There are also some fixes related to autoformatting in here, and it looks like the snapshots for some of the tests weren't updated to the pretty-printed JSON that we had introduced in a previous change, so I fixed that here. All tests are now passing again.
> respect aggs in exports

- app/graphql/types/field_display_type.rb
- app/graphql/types/site_agg_field_type.rb
- app/models/site_view.rb
- db/schema.rb
- front/app/components/SiteForm/AggField.tsx
- front/app/containers/AggDropDown/AggDropDown.tsx
- front/app/containers/AggDropDown/RangeSelector.tsx
- front/app/containers/SiteProvider/SiteProvider.tsx
- front/app/types/globalTypes.ts
-Allows user to configure the start/end description for the number range.
-Allows ability to hide the Start or End to have a Greater Than or Less Than Option
Screenshots:
In this first image is my Facet bar configuration. specifically my crowdAggs:
***Note that instead of adding additional fields to each agg field I created two new display types _Greater than Range_ and _Less Than Range_ ***
The following gif shows that configuration in action:
***Note the presearch is purposefully left as text displays to show they are independent of the facet bar config***
This final image shows the presearch display configured to match their title:
> 540 Additional Number Range Features

- front/app/queries/SearchPageCrowdAggBucketsQuery.ts
- front/app/types/SearchPageCrowdAggBucketsQuery.ts
I think this fixes not getting the :agg_options_sort in the backend, the query for it did not have the argument but the front end must have set a variable up but never passed it
> Front end not passing agg options sort in the query

- front/src/components/AuthHeader/UserProfileHeaderButton.tsx
- front/src/containers/App/App.tsx
- front/src/containers/BulkEditPage/BulkEditPage.tsx
- front/src/containers/StudyPage/StudyPage.tsx
- front/src/containers/StudyPage/components/StudyPageCounter/StudyPageCounter.tsx
-Makes _Edit Profile_  and the _X_ a link to make it more clear to the user it's clickable
-Makes the input boxes white so it is more clear to the user it's clickable
-The Star rank was off center previously 
-Themed the buttons in results section
-Small bug fix: Previously when adding more than one button in results and trying to set the icon and target to the second it would default back to just one button. 
The following gif shows all the user profile edits:
The image shows the results button themed:
> 576 take two

- front/src/containers/AggDropDown/BarChart.tsx
- front/src/containers/SearchPage/SearchPage.tsx
- front/src/containers/SearchPage/components/AggFilterInputUpdater.tsx
Previously when you added a series of aggFilters you hadn't visited before results appeared to load twice.
This PR fixes that issue by checking the input for the fields previously missing (gte, lte, and includeMissingFields) are defined. If not it sets them to null, this get's rid of the mismatch when building state from hash getting rid of the double load.
> 603 double load

- front/src/components/SlackCounter/SlackCounter.tsx
- front/src/containers/StudyPage/components/StudyPageHeader.tsx
Previously user couldn't click to increment a reaction if they hadn't reacted to that study with that reaction, but rather had to use the add reaction button
Currently if study is liked by other users only, not current user, clicking the like icon should add a like for the current user
> allows a reaction click to either create or delete reaction

- app/graphql/mutations/create_site.rb
- app/graphql/mutations/update_site.rb
- app/graphql/types/site_type.rb
- db/migrate/20200626152506_reaction_config.rb
- db/schema.rb
- front/src/components/SiteForm/MainForm.tsx
- front/src/components/SiteForm/SiteForm.tsx
- front/src/containers/SiteProvider/SiteProvider.tsx
- front/src/containers/StudyPage/StudyPage.tsx
- front/src/containers/StudyPage/components/StudyPageHeader.tsx
- front/src/types/CreateSiteMutation.ts
- front/src/types/SiteFragment.ts
- front/src/types/SiteProviderQuery.ts
- front/src/types/UpdateSiteMutation.ts
- front/src/types/globalTypes.ts
- front/src/utils/reactions/reactionKinds.ts
Allows for configuration of what reactions to display.
reactionsConfig at the site level holds a json string with an array of objects of the reactions we want to display. 
By default will display all (depicted by screenshot below)
This screenshot displays how I configured my site after
Followed by the output
> Reaction site config

- db/schema.rb
sites reaction_config changed to drop skull
@Tonyynot14 making sure that dropping the skull from the seed file won't break anything. Would prefer that be the default.
> drop skull reaction from default seed

- front/src/components/FacetCard/FacetCard.tsx
- front/src/containers/CrowdPage/AddCrowdLabel.tsx
- front/src/containers/CrowdPage/CrowdPage.tsx
In workflow sections previously the add label functionality was not working
-When adding a label from the "+" in the cards nothing would be added. This has been fixed and the value is now added.
However you dont see the value until you reload. 
- The add button in the All Crowd Labels section was also not working, there was a conditional block surrounding where 
the input box renders preventing it from rendering on a workFlow. Was this intentional? Should the circled input field (image below)  not 
be accessible in the workflow section?
Video of working add label from Cards:
https://slack-files.com/THRL5NEB0-F016YM6KE0G-86978f2a00
Post refresh of above video:
https://slack-files.com/THRL5NEB0-F01624GP51U-fda98bcc29
> 627 crowd label

- front/src/containers/SearchPage/SearchView2.tsx
- front/src/containers/SearchPage/components/MasonryCards.tsx
- front/src/global-styles.ts
Fix for bug while scrolling masonry cards, more of a workaround. 
Masonry does a bunch of additional work around cell measuring (which I believe might be part of the issue) which we don’t really leverage since we use a fixed height and width.
This solution uses the list component and style it to be sort of like a faux-masonry view.
> changes masonry cards to a list view styled like masonry cards

- app/graphql/types/site_search_page_type.rb
- app/models/site_view.rb
- front/src/components/SiteForm/AggField.tsx
- front/src/components/SiteForm/SearchForm.tsx
- front/src/components/StudySummary/StudySummary.tsx
- front/src/containers/SearchPage/SearchPage.tsx
- front/src/containers/SearchPage/SearchView2.tsx
- front/src/containers/SearchPage/components/CrumbsBar.tsx
- front/src/containers/SearchPage/components/ListCards.tsx
- front/src/containers/SearchPage/components/MasonryCards.tsx
- front/src/containers/SearchPage/components/TableRV.tsx
- front/src/containers/SiteProvider/SiteProvider.tsx
- front/src/global-styles.ts
- front/src/types/CopySiteViewMutation.ts
- front/src/types/CreateSiteMutation.ts
- front/src/types/CreateSiteViewMutation.ts
- front/src/types/CrowdPageQuery.ts
- front/src/types/EditReviewQuery.ts
- front/src/types/InterventionsPageQuery.ts
- front/src/types/SiteFragment.ts
- front/src/types/SiteProviderQuery.ts
- front/src/types/SiteViewFragment.ts
- front/src/types/StudyPagePrefetchQuery.ts
- front/src/types/StudyPageQuery.ts
- front/src/types/StudySummaryFragment.ts
- front/src/types/TagsPageQuery.ts
- front/src/types/UpdateSiteMutation.ts
- front/src/types/UpdateSiteViewMutation.ts
handles the first section of items of #682. 
Changes to sort:
placement, desc/asc icons, padding, etc.
Also shows working Recor count in breadcrumbs
RV Table: 
RV Table config:
> 682 requested changes

- front/src/components/MailMerge/MailMergeHelpers.ts
- front/src/components/MailMerge/MailMergeView.tsx
- front/src/components/StyledComponents/index.ts
- front/src/containers/GenericPage/GenericPage.tsx
- front/src/containers/Islands/NavigationIsland.tsx
- front/src/containers/Islands/ReviewsIsland.tsx
- front/src/containers/Islands/WikiPageIsland.tsx
- front/src/containers/SearchPage/SearchView2.tsx
- front/src/containers/SearchPage/components/TableRV.tsx
- front/src/utils/UrlParamsProvider.ts
-implements querystring ALL
-removes header formatting left over in some islands
-fixes navigation bug  that dropped pv value from querystring 
-adds rv table to use window scroller 
querystring ALL:
config
result: 
RV Table windowscroller:
Heading format removal:
> 682 requested changes cont'd

- front/src/components/MailMerge/MailMergeHelpers.ts
- front/src/containers/Islands/ReviewsIsland.tsx
- front/src/containers/Islands/WikiPageIsland.tsx
- front/src/containers/SearchPage/SearchView2.tsx
-Previously refactored navigation to use a new querystring all function to build the querystring wherever we need to push to a new link. This also implements on additional islands(wikipage, reviews) who also use the querystring. 
-additionally adds a new css class that can be accessed in the MM component to render certain islands in one line. See screenshots to see how to implement
> 682 Changes continued

- front/src/containers/SearchPage/components/MasonryCards.tsx
fixes #701  card(row) height bug when there's only 1 or 2 cards in search results.
> fix issue #701

- front/src/containers/Islands/BackIsland.tsx
Back button returns to search results page maintaining value of querystring
> fix for issue #702 

- front/src/containers/SearchPage/SearchView2.tsx
resolves #657. Search results renders the configured buttons to the different site views, button destination target links are working now and style consistent in all views w/ buttons located on top right side.
> fix for buttons search results

- front/src/components/SiteForm/SearchForm.tsx
- front/src/containers/SearchPage/SearchView2.tsx
resolves #710 , adds additional icon choices for results view buttons; list, small masonry and large masonry cards
list, small masonry and large masonry cards icons in order.
> 710 additional icons

- front/src/containers/SearchPage/SearchPage.tsx
- front/src/containers/SearchPage/SearchView2.tsx
- front/src/containers/SiteProvider/SiteProvider.tsx
- front/src/types/CreateSiteMutation.ts
- front/src/types/SiteFragment.ts
- front/src/types/SiteProviderQuery.ts
- front/src/types/UpdateSiteMutation.ts
Page view fragment in site provider, page view is pulled from page view query instead of hardcoded
related to 657 button is now using the current page’s querystring to keep same pv= after navigating to the target site view.
> 703 and 657 Page view fragment in site provider & pv in querystring

- .gitignore
- config/routes.rb
- public/loaderio-8d814a5de952773390cc25ce466a6b68.txt
- Add loader.io domain verification file
- Add standard `.gitignore` files for macOS
> Add loader.io domain verification file for load testing

- .gitignore
- config/routes.rb
- public/loaderio-21df9bee0c48bbdb7696ea087e1c5492.txt
- public/loaderio-8d814a5de952773390cc25ce466a6b68.txt
- public/loaderio-f076138abbb7fbc078ad112a429b504f.txt
- Change loader.io domain verification key to the one for www subdomain
- Add standard `.gitignore` files for Windows
> Change loader.io domain verification key to the one for www subdomain

- front/src/components/AuthHeader/AuthHeader.tsx
@awestermann Since the about page isn't part of the application really, I think it makes sense to open it in a new tab even if the app is not inside an iframe.
> Open about us in new tab

- README.md
Removing Vagrant instructions from `README.md` as discussed with @rodctech and @Tonyynot14 . The project does not have a Vagrantfile so I'm assuming this was left in by accident.
> Remove Vagrant instructions from README

- app/graphql/types/query_type.rb
- app/services/search_service.rb
[CW-6](https://clinwiki.atlassian.net/browse/CW-6) - Modify ElasticSearch service to only return requested facets for workflow resolvers
> CW-6 - Modify ElasticSearch service to only return requested facets for workflow resolvers

- front/src/containers/WorkflowPage/SuggestedLabels.tsx
- front/src/types/SuggestedLabelsQuery.ts
completes #CW-7 adjusts client side to get needed crowd buckets values from state and adds the crowd buckets wanted as arguments to the query
> CW-7  update client-side query to pass params to filter crowd facets

- front/src/containers/SearchPage/SearchPage.tsx
As stated in the spike in issue #699 there was redundancy in how state was being updated. Solution was to consolidate those calls in a manner that made sense. The updateSearchParams  function in itself updates state so made sense to only call updateSearchParams  and remove the redundant setState.
> CW-35 Fix for issues with 'Default' and 'Clear' buttons

- front/src/containers/WorkflowPage/SuggestedLabels.tsx
Added the beat loader return on instead of null for suggested label query. This component actually loads the data. With a sleep timer on the rails side during the query the beat loader appeared on the page. Generally locally loads too fast.
> CW-38 - Added beat loader to page when loading

- front/src/containers/Islands/FacilityIsland.tsx
Makes the map a more reasonable height. Achieves this by making the height relative to the viewport size.
> CW-24 Shrink Map

- front/package.json
- front/yarn.lock
Update our fork of `react-rte` with changes from original repo since we forked it and use our fork as a dependency to get back the changes @ericharding originally made to open all links made in the WYSIWYG editor in a new tab
> CW-36 - A hyperlink configured to open in a new tab in the WYSIWYG editor does not actually open the link in the new tab

- front/src/components/SiteForm/AggField.tsx
Value field was incorrectly referencing the rank property of the agg. This fixes that and makes sure it is reading and referencing the displayName property which is what controls the Agg Label field
> CW-45 Agg label bug

- front/src/components/Edits/Edit.tsx
- front/src/components/Edits/EditBlurb.tsx
- front/src/components/Edits/Edits.tsx
- front/src/components/Edits/ExpandedEdit/ExpandedAsRawDiff.tsx
- front/src/components/Edits/ExpandedEdit/ExpandedEdit.tsx
- front/src/components/Edits/ExpandedEdit/FrontMatterExpandedEdit.tsx
- front/src/components/Edits/ExpandedEdit/WikiExpandedEdit.tsx
- front/src/containers/Islands/WikiPageIsland.tsx
[CW-17](https://clinwiki.atlassian.net/browse/CW-17) - Bring back history button
- Changed all components related to edit history to functional components
- Removed `ExpansionContext` since it was only being used by `EditBlurb` and `ExpandedEdit` so it doesn't make sense to re-render the whole `WikiPageIsland` component (from what I can see)
- Also seems to make more sense to keep the state management of each `Edit` component self-contained since it is not dependent on the state of other `Edit` components
> CW-17 - Bring back history button

- .example.env
- docker-compose.yml
- Remove staging database password from Docker Compose file and update `.example.env`
- Fix container volume path for Postgres so the data persists after `docker-compose down` 
Right now, the database container loses all its data when we destroy the container even though we have assigned a volume for it. Turns out, there is a specific directory where Postgresql requires you to store persistent data.
See Postgres docs and the `Where to Store Data` section of the Docker image [documentation](https://hub.docker.com/_/postgres) for more details.
It won't make deploying the environment variable changes easier this time but in the future, we should be able apply environment or Docker Compose configuration changes without destroying the staging or development data. This time, we will still have …
> Remove staging database password from Docker Compose file and fix database volume persistence issue 

- front/src/components/SiteForm/AggField.tsx
The way our display label works is we have the `displayName` and original `name` in the aggs and crowdAggs properties. To make the aggs more readable we use the aggToFields. I Naively just used that for our value. When I should have included a case for crowdAggs which aren't listed in the aggToFields causing it to default to the `name`. So even though our changes where being made to the `displayName`  field, what was being displayed was the `name` field making it seem like nothing was happening.
> CW-45 - logic to handle displayValue for crowdAggs

- front/src/containers/Islands/EditsHistoryIsland/EditsHistory.tsx
- front/src/containers/Islands/EditsHistoryIsland/EditsHistoryButtons.tsx
- front/src/containers/Islands/EditsHistoryIsland/index.tsx
Fix for our WikiHistory Island not displaying:
Was a two part issue routing and error handling
*Note I also changed the button that closes the history altogether to say close. Previously said "View" to return back to the regular wiki page, however no longer the case.
Bonus: 
Config Picture
> route path updates for the wiki history

- front/src/containers/SearchPage/SearchPage.tsx
Previously our view on anything ipad or smaller would make the facet bar on top of our Search View made it hard to get to results when large lists of facets in a View. To mitigate that thought mimicking something like Jira where they collapse the side bar might make for better user experience.
> CW-74- makes facet bar collapsible

- front/src/containers/SearchPage/SearchPage.tsx
Just took some state update consolidation as well as making sure we update our default_params with our q querystring value
> CW-55-handles q coming from home.clinwiki

- front/src/containers/SearchPage/SearchPage.tsx
Reverts clinwiki-org/clinwiki#803
this seems to be breaking the facet selections in facet bar and presearch
> Revert "Revert "Revert "CW-55-handles q coming from home.clinwiki"""

- front/src/global-styles.ts
Css changes for font-family of pre tag. Did not see any wrapping issues
> Global style change for pre in mail-merge, makes it inherit font-family

- front/src/containers/SearchPage/SearchView2.tsx
Previously even when results where not being shown to the user we where querying the data used to display it. This changes that so that we aren't query study data if it isn't being shown. This is in hopes to boost performance on siteviews with no results displaying.
> CW-85 Seperate query created to call when results hidden

- front/src/components/WikiPageEditor/WikiPageEditor.tsx
- front/src/containers/Islands/WikiPageIsland.tsx
- front/src/hooks/useUnload.ts
- Remove `Preview` button
- Remove `Markdown` button
- When user clicks the `Edit` button, it should change to a disabled `Save` button
- When user makes an edit to the text, the `Save` button should be enabled
- When user clicks `Save`, the button should change back to `Edit`
- If user tries to close the tab or their browser without saving their changes, they should be warned and given the option to keep the tab open so they can save
> Cw 60 wikipage rework

- front/src/containers/SearchPage/SearchPage.tsx
As a temporary fix sets fetch policy to network only for query SearchPageParamsQuery, it skips the use of cache and will force network request to get the data. (does not help performance) 
Sort order button toggle is working continuously.
> CW-62 Temp fix for sort order button

- front/src/containers/SearchPage/SearchView2.tsx
- front/src/global-styles.ts
Additional global style defined to help improve the look of the crwod tags. 
*Additionally snuck into this:  changed name of the added query in PR #809 previously left the same but when restarting enviornment causes error because that query already exists.
> RTM: CW-79-Improves display of crowd tags 

- front/src/containers/SearchPage/SearchView2.tsx
changed name of the added query in PR #809, previously left the same but when restarting environment causes error because that query already has been defined.
> RTM: Update SearchView2.tsx

- front/src/components/SiteForm/SearchForm.tsx
- front/src/containers/SearchPage/SearchPage.tsx
- front/src/containers/SearchPage/SearchView2.tsx
Taken from issue #723 removes the old siteviews as options along with any related code. 
There where a pretty good bunch of unused functions and leftover code I was able to clean up. 
In addition if any old view options  are still out there it defaults to card view and displays a message (see screenshot below)
List of available views
> CW-50 Remove old views

- front/src/containers/SearchPage/SearchPage.tsx
- front/src/containers/SearchPage/SearchView2.tsx
- front/src/containers/SearchPage/Types.ts
- front/src/containers/SearchPage/components/Aggs.tsx
- front/src/types/SearchPageAggsQuery.ts
- front/src/types/SearchPageSearchQuery.ts
- front/src/types/SearchPageSearchQueryNoResults.ts
First step in our refactor.
Removes CrowdAggs and Aggs from our State in SearchPage 
Instead each component queries only the data it needs. 
After implementing cut reloads by about 30%
> CW-100 refactor search page

- front/src/containers/AggDropDown/Bucket.tsx
Switch statement expected a int value from 0-5 and was getting decimal values,  0.0 for example.
Not sure at what point the average rating changed from a int to a decimal or if we where handling the parsing somewhere that might have been accidently removed.  In any case added the handling of that into the buckets where it was broken and seems to be back in working order.
> CW-76 Bug- Average rating displaying undefined instead of stars 

- front/src/components/WikiPageEditor/WikiPageEditor.tsx
- front/src/containers/Islands/WikiPageIsland.tsx
-Prompts user before navigation ( back in browser, back to search results, admin console, next, first, etc.) to verify before leaving page while editing the Wiki section is active.
-On save button prompt to verify save of current changes.
> CW-93 Wiki edits warn user of unsaved before leaving page.

- front/src/components/AuthHeader/AuthHeader.tsx
- front/src/containers/SearchPage/SearchPage.tsx
1. Urls with no hash get hash based on site params in componentDidMount
2. When clicking on the logo we were getting caught in loop due to a hash update/params update state war. The fix is probably a continuing refactor of some of the searchpage flow of operations. for quick fix we are reloading the entire page when a user clicks on the logo which then just reverts to step 1. Not great but should work for the time being.
> Cw 107 default bug

- front/src/components/StyledComponents/index.ts
- front/src/containers/AggDropDown/AggDropDown.tsx
Fixed redudant presearch container styles that were affecting the dropdown container and also creating really messed up margins on other presearch panels.
Fixed curved presearch headers.
> fixing default presearch content and panel styles

- app/services/study_edge_service.rb
This pr changes .search to .search_without_aggs in app/services/study_edge_service.rb
> calling search_without_aggs from study_edge

- front/src/containers/ReviewForm/ReviewForm.tsx
After a user submits a review brings them back to the previous screen displaying the reviews. Achieves this by pushing user away from the `/new` route that gets appended to the url when we click `Write a Review`.
Small edit but large improvement in user experience in my opinion.
> CW-68-Reviews Flow

- front/src/components/MailMerge/MailMergeHelpers.ts
Previously truncate appended the ellipses at the end of the value even if it was within the character limit. Therefore when hovering over the ellipses nothing was displayed. Conditional check if it's within character bounds will just return value. 
First Screenshot illustrates the old behavior. 
This GIF tries to illustrate the new and originally desired behavior.
> CW-124 truncate showing ellipses when necessary

- front/src/components/MailMerge/MailMergeHelpers.ts
Can now feed a series of pipe separated strings to include in your find and replace. In the example I have recruiting, available, suspended, and terminated as the values I am looking for with their respective replacements (also pipe separated). 
Attached is the results
> CW-119 Find and Replace next iteration 

- config/puma.rb
commented out worker_timeout (24*60*60) if ENV['RAILS_ENV']=='development' in config/puma
> removed a config from config/puma for development

- front/src/components/SiteForm/AggField.tsx
- front/src/containers/AggDropDown/AggDropDown.tsx
Makes preselected values & visible options on siteview config aggs show as checkboxes
> CW-129 fix for config preselected and visible options

- front/src/containers/AggDropDown/AggDropDown.tsx
Sets any values that are null to render filter bar. The only caveat is that for old siteviews the filterbar check will be unchecked despite the filter showing up in the facetbar. So to hide it you would need to check it to true (no longer null) and then uncheck it back to false.
> Fix for missing filter-bar on facet bar and presearch

- app/helpers/bulk_update_helper.rb
Previously read wiki_page from study use to be StudyType which included wiki_page field. But now is of ElasticStudyType and does not contain wiki_page. As a fix we query for the WikiPage directly from ActiveRecord.
> CW-192 Bulk Update Bug Patch 

- front/src/containers/SearchPage/components/Aggs.tsx
Buckets was redundant as it gets queried again when agg opens
> Cw-198 remove buckets from AggsQuery

- front/src/containers/SearchPage/components/Aggs.tsx
Incorrectly was querying for crowdAgg "name" field which always just returned "front-matterkeys"
should really have been querying for the bucket keys which is what we use to build the crowd aggs
> Fix for crowd aggs disappearing

- front/src/containers/SearchPage/SearchPage.tsx
Tracked down the behavior to when the component initially was loaded with a hash our params.current was never updated to reflect what our searchParamsQuery returned the params to be based on hash. So was defaulting to a cleared version of params. 
Now onComplete of that query we update params.current with the params returned from the query.
> CW-221 "search within" clearing filters

- front/src/containers/GenericPage/GenericPage.tsx
- front/src/containers/Islands/WorkflowIsland.tsx
- front/src/containers/WorkflowPage/SuggestedLabels.tsx
Previously when interacting with the workflow on a pageview your entire page would reload. 
As of now, there is no reload on unchanged islands (i.e. facility or wikipage).  We only see a reload of the workflow island istelf.
> Persist unchanged data during reload using previousData

- app/models/wiki_page.rb
if import file missing valid user_email value, "updater" is not available and insert fails. Improving error message
> change error message for user_email missing in import

- .vscode/settings.json
- front/src/containers/AggDropDown/AggDropDown.tsx
- front/src/containers/AggDropDown/AggKeyValuePairsDropDown.tsx
- front/src/containers/AggDropDown/AllowMissingDropDownItem.tsx
- front/src/containers/AggDropDown/CustomDrop.tsx
- front/src/containers/AggDropDown/CustomDropCrumbs.tsx
- front/src/containers/AggDropDown/CustomDropPanel.tsx
- front/src/containers/SearchPage/components/Aggs.tsx
Fix for a few bugs with new presearch
CW-261: Average Rating and remaining Drop Down Field Types
CW-302: Allow Missing not showing up as an option
CW-282: Presearch Crumbs not working for location and range filters
CW-259: Facet bar only opens 1 agg at a time
Last but not least. Prior to this breadcrumbs would auto show all if panel was open. That behavior is no more.
> Presearch bugs

- front/src/components/FacetCard/FacetCard.tsx
- front/src/components/FacetCard/FacetCardCheckbox.tsx
- front/src/containers/WorkflowPage/SuggestedLabels.tsx
Created new component FacetCardCheckbox, where UI checkbox state is decoupled from the value of the checkboxes in the database. (Because SuggestedLabelsQuery and front matter parsing takes long)
No node branch, fix bug CW-352 no lag updating crowd bucket values.
> NoNode branch, fix bug CW-352 no lag updating crowd bucket values.

- front/src/global-styles.ts
Can add in theme color assuming you plan on using same syntax as they did in the w3 article.  Just wanted to make sure this is what you were looking for. 
`
///TOOL TIPS
.tooltip {
position: relative;
display: inline-block;
}
.tooltip .tooltiptext {
visibility: hidden;
width: 120px;
background: rgba(0,0,0,.7);
color: #fff;
text-align: center;
border-radius: 6px;
padding: 5px 0;
/* Position the tooltip */
position: absolute;
z-index: 1;
opacity: 0;
transition: .5s;
}
.tooltip:hover .tooltiptext {
visibility: visible;
opacity: 1;
top: -20px;
}`
> tooltip css

- api/src/search/translator.js
- front/src/containers/AggDropDown/Filter.tsx
- front/src/containers/Islands/IslandAggChild.tsx
- front/src/services/search/actions.ts
- front/src/services/search/reducer.ts
- front/src/services/search/sagas.ts
- front/src/services/search/types.ts
Restores aggBuckets Filter functionality 
Required changes in the translator as well as in our front-end code. 
Local state was holding our filter values prior and was being very problematic. Moved it to redux to solve most of our issues. (Should note I think our other state values can also benefit from a similar refactor  i.e. sort )
*** Current Caveat is No Karnofsky Facet can be defaulted to Open
> Buckets filter

- api/src/pipeline/jobs/indexDoc.job.js
- api/src/util/graphqlToIndexMapping.js
added generic index for studies for browse_condtions, browse_interventions and central_contacts to the graphql query and mapping
> add browse interv, cond, contact

- front/src/components/MailMerge/MMTestComponent.tsx
- front/src/components/MailMerge/MMTestComponentWrapper.tsx
- front/src/containers/App/App.tsx
Restores MMtest functionality. 
Refactored it to fit more of the new Generic Page Needs. 
No need to input NCT or hash anymore, or starter template. Have it reading from pv
Example: 
Lets say  I want to test new feature on presearch pv currently at http://experimental.clinwiki.org/search?hash=gELcp_Fb&pv=presearch 
Just change route from search  to mmtest and should pre-load the template. 
http://experimental.clinwiki.org/mmtest?hash=gELcp_Fb&pv=presearch 
works with studies as well 
http://experimental.clinwiki.org/study/NCT03196414?hash=gELcp_Fb&pv=study 
http://experimental.clinwiki.org/mmtest/NCT03196414?hash=gELcp_Fb&pv=study
This final screenshot shows the different parts of the page that are collapsible
> Mmtest refatctor

- front/src/containers/Islands/StudyInfiniteScroll.tsx
Only select fields where being passed down through context into mm studyinfiniteascroll component. 
As a fix, passed in whole study object. This will need some refactoring in the future to generalize this island and make it accessible to all page types
> fix context limited in studyinfinitescroll island

- api/schema.graphql
- api/src/pipeline/jobs/indexDoc.job.js
Our Index Jobs run off the SAMPLE_QUERY_CLINWIKI. 
- To make sure the fields make it to our index we simply make sure they are in said query (indexed_at gets added by the backend once the index job is processing, hence why it isn't in the query)
- To add them/access them in our pv/results we have to make sure it is in our  schema.graphql file in our ElasticStudyObject. For whatever reason (ruby => node) it has to be camelCased. Some place in our code it converts it back to snake_case, looked for it briefly but was not obvious at first glance so keep an eye out for the PR to remove that in future. 
Sample use in template and how it renders :
> add values to index and gql
